import type { Metadata } from "next";
import { Legal } from "@/components/legal";

export const metadata: Metadata = { title: "Terms — Creora", description: "Terms of using Creora." };

export default function TermsPage() {
  return (
    <Legal
      title="Terms of Service"
      intro="The basics of using Creora. (This is a general summary and not legal advice.)"
      sections={[
        { heading: "Use of the service", body: "Creora provides AI-assisted tools for content ideas, scripts, repurposing, and growth recommendations. You're responsible for how you use the outputs." },
        { heading: "Your account", body: "You're responsible for keeping your account secure and for activity under your account." },
        { heading: "AI-generated outputs", body: "Outputs are generated by AI and may be inaccurate or need editing. Review everything before publishing." },
        { heading: "No guarantee of results", body: "Creora does not guarantee growth, views, revenue, or any specific outcome." },
        { heading: "Subscriptions & payments", body: "Paid plans, where applicable, are billed per the plan you choose. (TODO: confirm billing terms once payments are live.)" },
        { heading: "Contact", body: "Questions? Email support@creora.pro." },
      ]}
    />
  );
}
