"use client";
import { useState } from "react";
import { Brain, Loader2, Copy, Check, BookMarked } from "lucide-react";
import { Card, Badge, PageHeader } from "@/components/ui/primitives";
import { cn } from "@/lib/utils";

const TYPES = [
  { id: "titles", label: "Titles" },
  { id: "hooks", label: "Hooks" },
  { id: "script", label: "Script outline" },
  { id: "tweet", label: "X thread" },
  { id: "linkedin", label: "LinkedIn post" },
  { id: "blog", label: "Blog" },
];

const PROMPTS = [
  "Budget studio setups under $200",
  "AI tools that replaced my $5k gear",
  "Why your B-roll looks cheap",
];

export default function BrainPage() {
  const [type, setType] = useState("titles");
  const [topic, setTopic] = useState("Budget studio setups under $200");
  const [out, setOut] = useState<string | null>(null);
  const [live, setLive] = useState<boolean | null>(null);
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [saved, setSaved] = useState(false);

  async function saveToVault() {
    if (!out) return;
    const kind = type === "script" ? "Script" : type === "hooks" ? "Hook" : type === "titles" ? "Hook" : "Template";
    await fetch("/api/vault", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ kind, title: `${topic}`, tags: [type] }),
    });
    setSaved(true);
    setTimeout(() => setSaved(false), 1800);
  }

  async function run() {
    setLoading(true); setOut(null);
    try {
      const res = await fetch("/api/ai/generate", { method: "POST", body: JSON.stringify({ type, topic }) });
      const data = await res.json();
      setOut(data.text); setLive(data.live);
    } finally { setLoading(false); }
  }
  function copy() { if (out) { navigator.clipboard.writeText(out); setCopied(true); setTimeout(() => setCopied(false), 1500); } }

  return (
    <div>
      <PageHeader icon={<Brain size={18} />} title="AI Content Brain" subtitle="Generate ideas, hooks, titles, scripts, posts — on-brand, in your voice, across GPT / Claude / Gemini." />

      <div className="grid gap-4 lg:grid-cols-[1fr_1.1fr]">
        <Card>
          <div className="label mb-1.5">What to generate</div>
          <div className="flex flex-wrap gap-1.5">
            {TYPES.map((t) => (
              <button key={t.id} onClick={() => setType(t.id)} className={cn("rounded-lg border px-3 py-1.5 text-sm transition-colors", type === t.id ? "border-brand bg-brand/15 text-ink" : "border-line bg-bg-elevated text-ink-muted hover:text-ink")}>{t.label}</button>
            ))}
          </div>

          <div className="label mb-1.5 mt-4">Topic</div>
          <textarea value={topic} onChange={(e) => setTopic(e.target.value)} rows={3} className="input resize-none" />
          <div className="mt-2 flex flex-wrap gap-1.5">
            {PROMPTS.map((p) => <button key={p} onClick={() => setTopic(p)} className="chip hover:text-ink">{p}</button>)}
          </div>

          <div className="mt-4 flex items-center gap-2">
            <button onClick={run} disabled={loading} className="btn-primary">
              {loading ? <><Loader2 size={15} className="animate-spin" /> Generating…</> : "Generate"}
            </button>
            <Badge tone="brand">Model: Claude</Badge>
            <span className="text-xs text-ink-faint">router picks best model per task</span>
          </div>
        </Card>

        <Card>
          <div className="mb-2 flex items-center justify-between">
            <span className="text-sm font-medium text-ink">Output</span>
            {out && <div className="flex items-center gap-1.5">
              <button onClick={saveToVault} className="btn-subtle h-7 px-2 text-xs">{saved ? <><Check size={13} /> Saved</> : <><BookMarked size={13} /> Save to Vault</>}</button>
              <button onClick={copy} className="btn-subtle h-7 px-2 text-xs">{copied ? <><Check size={13} /> Copied</> : <><Copy size={13} /> Copy</>}</button>
            </div>}
          </div>
          {!out && !loading && <div className="rounded-lg border border-dashed border-line bg-bg-soft px-4 py-10 text-center text-sm text-ink-faint">Pick a type and topic, then hit Generate.</div>}
          {loading && <div className="flex items-center justify-center gap-2 py-10 text-sm text-ink-muted"><Loader2 size={16} className="animate-spin" /> Thinking…</div>}
          {out && (
            <div className="rounded-lg border border-line bg-bg-soft p-4">
              <p className="whitespace-pre-wrap text-sm leading-relaxed text-ink">{out}</p>
              {live === false && <span className="mt-3 block text-[10px] text-ink-faint">· fallback mode — add ANTHROPIC_API_KEY in .env.local for live AI</span>}
              {live === true && <span className="mt-3 block text-[10px] text-mint">· live · generated by Claude</span>}
            </div>
          )}
        </Card>
      </div>

      <Card className="mt-4">
        <div className="text-sm font-medium text-ink">Prompt Library</div>
        <div className="mt-3 grid gap-2 sm:grid-cols-3">
          {["Hook: contrarian budget angle", "Title: number + outcome", "Script: open-loop opener", "Thread: 7-tweet breakdown", "Description: SEO + timestamps", "Community post: poll"].map((p) => (
            <div key={p} className="rounded-lg border border-line bg-bg-soft px-3 py-2 text-sm text-ink-muted hover:border-brand/40 hover:text-ink">{p}</div>
          ))}
        </div>
      </Card>
    </div>
  );
}
